file = open('sample.txt', 'r')
file2 = open('sample.txt', 'w')
file3 = open('sample.txt', 'a')
#content = file.read()
#line = file.readline()
#lines = file.readlines()
#print(content)
#print(line)
#print(lines)
file2.write('this is the writing2 of a line\n')
file3.write('this is the appended line\n')
file.close()